package com.example.meditrack.ui.theme

import androidx.compose.ui.graphics.Color

// Custom health/wellness-oriented Material 3 color palette
// Light Theme Colors
val LightPrimary = Color(0xFF00696B)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE0F7F7) // Soft Minty Teal
val LightOnPrimaryContainer = Color(0xFF002021)
val LightSecondary = Color(0xFF4A6363)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD3EAEB)
val LightOnSecondaryContainer = Color(0xFF051F20)
val LightTertiary = Color(0xFF4B607C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD3E4FF)
val LightOnTertiaryContainer = Color(0xFF041C35)
val LightBackground = Color(0xFFFAFDFD)
val LightOnBackground = Color(0xFF191C1C)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF191C1C)
val LightSurfaceVariant = Color(0xFFE0EAEA)
val LightOnSurfaceVariant = Color(0xFF3F4948)
val LightOutline = Color(0xFF707979)

// Dark Theme Colors
val DarkPrimary = Color(0xFF80D4D6)
val DarkOnPrimary = Color(0xFF003738)
val DarkPrimaryContainer = Color(0xFF004F50)
val DarkOnPrimaryContainer = Color(0xFF9CF0F2)
val DarkSecondary = Color(0xFFB1CBCB)
val DarkOnSecondary = Color(0xFF1C3535)
val DarkSecondaryContainer = Color(0xFF324B4C)
val DarkOnSecondaryContainer = Color(0xFFCDE7E7)
val DarkTertiary = Color(0xFFB3C8E8)
val DarkOnTertiary = Color(0xFF1C314B)
val DarkTertiaryContainer = Color(0xFF334863)
val DarkOnTertiaryContainer = Color(0xFFD3E4FF)
val DarkBackground = Color(0xFF111414)
val DarkOnBackground = Color(0xFFE0E3E3)
val DarkSurface = Color(0xFF111414)
val DarkOnSurface = Color(0xFFE0E3E3)
val DarkSurfaceVariant = Color(0xFF3F4948)
val DarkOnSurfaceVariant = Color(0xFFBEC8C7)
val DarkOutline = Color(0xFF899392)

// Expiry and Status colors (M3 aligned)
val ExpiryGreen = Color(0xFF2E7D32)
val ExpiryOrange = Color(0xFFEF6C00)
val ExpiryRed = Color(0xFFC62828)

// --- Custom Color Themes ---

// 1. Blue Theme
val BluePrimary = Color(0xFF1976D2)
val BlueOnPrimary = Color(0xFFFFFFFF)
val BluePrimaryContainer = Color(0xFFD1E4FF)
val BlueOnPrimaryContainer = Color(0xFF001D36)
val BlueSecondary = Color(0xFF535F70)
val BlueSecondaryContainer = Color(0xFFD7E3F7)
val BlueTertiary = Color(0xFF6B5778)
val BlueTertiaryContainer = Color(0xFFF2DAFF)
// Dark Blue
val BluePrimaryDark = Color(0xFF9ECAFF)
val BlueOnPrimaryDark = Color(0xFF003258)
val BluePrimaryContainerDark = Color(0xFF00497D)
val BlueOnPrimaryContainerDark = Color(0xFF9ECAFF)
val BlueSecondaryDark = Color(0xFFBBC7DB)
val BlueSecondaryContainerDark = Color(0xFF3B4858)
val BlueTertiaryDark = Color(0xFFD7BDE4)
val BlueTertiaryContainerDark = Color(0xFF523F5F)

// 2. Purple Theme
val PurplePrimary = Color(0xFF6750A4)
val PurpleOnPrimary = Color(0xFFFFFFFF)
val PurplePrimaryContainer = Color(0xFFEADDFF)
val PurpleOnPrimaryContainer = Color(0xFF21005D)
val PurpleSecondary = Color(0xFF625B71)
val PurpleSecondaryContainer = Color(0xFFE8DEF8)
val PurpleTertiary = Color(0xFF7D5260)
val PurpleTertiaryContainer = Color(0xFFFFD8E4)
// Dark Purple
val PurplePrimaryDark = Color(0xFFD0BCFF)
val PurpleOnPrimaryDark = Color(0xFF381E72)
val PurplePrimaryContainerDark = Color(0xFF4F378B)
val PurpleOnPrimaryContainerDark = Color(0xFFEADDFF)
val PurpleSecondaryDark = Color(0xFFCCC2DC)
val PurpleSecondaryContainerDark = Color(0xFF4A4458)
val PurpleTertiaryDark = Color(0xFFEFB8C8)
val PurpleTertiaryContainerDark = Color(0xFF633B48)

// 3. Green Theme
val GreenPrimary = Color(0xFF386A20)
val GreenOnPrimary = Color(0xFFFFFFFF)
val GreenPrimaryContainer = Color(0xFFB8F397)
val GreenOnPrimaryContainer = Color(0xFF042100)
val GreenSecondary = Color(0xFF55624C)
val GreenSecondaryContainer = Color(0xFFD9E7CB)
val GreenTertiary = Color(0xFF19686A)
val GreenTertiaryContainer = Color(0xFFA8EFF0)
// Dark Green
val GreenPrimaryDark = Color(0xFF9CD67D)
val GreenOnPrimaryDark = Color(0xFF0C3900)
val GreenPrimaryContainerDark = Color(0xFF205107)
val GreenOnPrimaryContainerDark = Color(0xFFB8F397)
val GreenSecondaryDark = Color(0xFFBDCBB0)
val GreenSecondaryContainerDark = Color(0xFF3E4A36)
val GreenTertiaryDark = Color(0xFF8CD2D4)
val GreenTertiaryContainerDark = Color(0xFF004F50)

// 4. Orange Theme
val OrangePrimary = Color(0xFF8B5000)
val OrangeOnPrimary = Color(0xFFFFFFFF)
val OrangePrimaryContainer = Color(0xFFFFDCC1)
val OrangeOnPrimaryContainer = Color(0xFF2E1600)
val OrangeSecondary = Color(0xFF745A45)
val OrangeSecondaryContainer = Color(0xFFFFDEC7)
val OrangeTertiary = Color(0xFF5C6237)
val OrangeTertiaryContainer = Color(0xFFE1E7B1)
// Dark Orange
val OrangePrimaryDark = Color(0xFFFFB85E)
val OrangeOnPrimaryDark = Color(0xFF4A2800)
val OrangePrimaryContainerDark = Color(0xFF6A3C00)
val OrangeOnPrimaryContainerDark = Color(0xFFFFDCC1)
val OrangeSecondaryDark = Color(0xFFE3C2A9)
val OrangeSecondaryContainerDark = Color(0xFF5A4330)
val OrangeTertiaryDark = Color(0xFFC5CB97)
val OrangeTertiaryContainerDark = Color(0xFF454B22)

